== 1. BrandController

=== 1-1. 브랜드 생성

operation::brand-documentation-test/create-brand[snippets="request-fields,http-request,http-response"]

=== 1-2. 브랜드 단일 조회

operation::brand-documentation-test/get-brand[snippets="path-parameters,http-request,response-fields-data,http-response"]

=== 1-3. 브랜드 수정

operation::brand-documentation-test/update-brand[snippets="path-parameters,request-fields,http-request,http-response"]

== 2. StoreController

=== 2-1. 스토어 생성

operation::store-documentation-test/create-store[snippets="request-fields,http-request,http-response"]

=== 2-2. 스토어 단일 조회

operation::store-documentation-test/get-store[snippets="path-parameters,http-request,response-fields-data,http-response"]

=== 2-3. 스토어 다중 조회

operation::store-documentation-test/get-all-stores[snippets="http-request,response-fields-data,http-response"]

=== 2-4. 스토어 수정

operation::store-documentation-test/update-store[snippets="path-parameters,request-fields,http-request,http-response"]

== 3. MenuController

=== 3-1. 메뉴 생성

operation::menu-documentation-test/create-menu[snippets="path-parameters,request-fields,http-request,http-response"]

=== 3-2. 메뉴 단일 조회

operation::menu-documentation-test/get-menu[snippets="path-parameters,http-request,response-fields-data,http-response"]

=== 3-3. 메뉴 다중 조회

operation::menu-documentation-test/get-all-menus[snippets="path-parameters,http-request,response-fields-data,http-response"]

=== 3-4. 메뉴 수정
operation::menu-documentation-test/update-menu[snippets="path-parameters,request-fields,http-request,http-response"]

== 4. CouponController

=== 4-1. 어드민 쿠폰 생성

operation::coupon-documentation-test/create-admin-coupon[snippets="request-fields,http-request,http-response"]

=== 4-2. 스토어 쿠폰 생성

operation::coupon-documentation-test/create-store-coupons[snippets="path-parameters,request-fields,http-request,http-response"]

== 5. MemberCouponController

=== 5-1. 미할당 쿠폰 생성(쿠폰 코드 생성)

operation::member-coupon-documentation-test/issue-coupon-codes[snippets="path-parameters,request-fields,http-request,http-response"]

=== 5-2. 쿠폰 할당(클릭)

operation::member-coupon-documentation-test/allocate-member-coupon-by-click[snippets="path-parameters,http-request,http-response"]

=== 5-3. 쿠폰 할당(코드)

operation::member-coupon-documentation-test/allocate-member-coupon-by-code[snippets="request-fields,http-request,http-response"]

=== 5-4. 멤버 쿠폰 조회

operation::member-coupon-documentation-test/get-all-member-coupons[snippets="http-request,response-fields-data,http-response"]

=== 5-5. 주문 중 사용 가능 쿠폰 조회

operation::member-coupon-documentation-test/get-all-available-member-coupons[snippets="path-parameters,http-request,response-fields-data,http-response"]

== 6. OrderController

=== 6-1. 주문 생성

operation::order-documentation-test/create-order[snippets="path-parameters,request-fields,http-request,http-response"]

=== 6-2. 주문 상세 조회

operation::order-documentation-test/get-order[snippets="path-parameters,http-request,response-fields-data,http-response"]

=== 6-3. 주문 리스트 조회

operation::order-documentation-test/get-all-orders[snippets="http-request,response-fields-data,http-response"]

=== 6-4. 가게 주문 리스트 조회

operation::order-documentation-test/get-all-store-orders[snippets="path-parameters,http-request,response-fields-data,http-response"]

=== 6-5. 주문 수락(가게)

operation::order-documentation-test/update-order-status-to-preparing[snippets="path-parameters,http-request,http-response"]

=== 6-6. 주문 완료(가게)

operation::order-documentation-test/update-order-status-to-complete[snippets="path-parameters,http-request,http-response"]

== 7. PaymentController

=== 7-1. 결제 생성

operation::payment-documentation-test/create-payment[snippets="path-parameters,request-fields,http-request,http-response"]

=== 7-2. 결제 완료

operation::payment-documentation-test/complete-payment[snippets="path-parameters,http-request,http-response"]